language: php
php:
  - 5.4
  - 5.6
  - hhvm
  
before_script:
  - composer install
  - mysql -e 'create database sitahta;'
  - mysql sitahta < sitahta.sql
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('zaraki') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - vendor/bin/doctrine orm:schema-tool:drop --force
  - vendor/bin/doctrine orm:schema-tool:create
  
script:
  - phpunit #default test command
