language: php
php:
  - 5.4
  - 5.6
  - hhvm
  
before_script:
  - composer install
  - vendor/bin/doctrine orm:schema-tool:drop --force
  - vendor/bin/doctrine orm:schema-tool:create
  
script:
  - phpunit #default test command
