language: php
php:
  - 5.4
  - 5.6
  - hhvm
  
before_script:
  - mysql -e 'create database sitahta;'
  - mysql -e "use sitahta;CREATE TABLE IF NOT EXISTS user (nip varchar(15) NOT NULL, password varchar(512) NOT NULL, nama varchar(40) NOT NULL, PRIMARY KEY (nip));"
  - mysql -e 'SET sql_mode=ANSI_QUOTES;use sitahta;INSERT INTO user set nip = 1;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('zaraki') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - composer install
  
script:
- phpunit #default test command
