language: php
php:
  - 5.4
  - 5.6
  - hhvm
  
before_script:
  - mysql -e 'create database sitahta;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('zaraki') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
